const PlantPropertiesData =[
    {
        plant_id:1,
        cycle:'Многолетний',
        sun:'Солнцелюбивое',
        watering:'среднее',
        propagation:'вегетативными органами - усами',
        flowers:'Белые с желтым центром, Цветут весной',
        fruits:'Красные, желтые, розовые, белые. Вызревают летом',
        edible:'Съедобные',
        leaf:'Да',
        leaf_color:'Зеленые',
        growth_rate:'Высокая',
        maintenance:'Сложное',
        createdAt: new Date(),  
        updatedAt: new Date(),
    },
    {
        plant_id:2,
        cycle:'Многолетний',
        sun:'Полутень',
        watering:'умеренное',
        propagation:'вегетативными органами - усами',
        flowers:'нет',
        fruits:'нет',
        edible:'Несъедобное',
        leaf:'Да',
        leaf_color:'Зеленые',
        growth_rate:'Медленная',
        maintenance:'Сложное',
        createdAt: new Date(),  
        updatedAt: new Date(),
    },
    {
        plant_id:3,
        cycle:'Многолетний',
        sun:'Солнцелюбивое',
        watering:'регулярный',
        propagation:'семенами',
        flowers:'зеленые',
        fruits:'нет',
        edible:'Несъедобное',
        leaf:'Да',
        leaf_color:'Зеленые',
        growth_rate:'Высокая',
        maintenance:'Сложное',
        createdAt: new Date(),  
        updatedAt: new Date(),
    },
];

module.exports = PlantPropertiesData